### ISSUE TITLE
An error occurred while executing "make" in the terminal

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/TourExec#10]
Here is my Equipment specification：
![bb89a7dc12cf640d4aba0022d42e620_译图](https://github.com/Axelrod-Python/TourExec/assets/111236370/72362a1d-c7e2-4792-b3d6-4817cca127b1)

My make and gfortran have been downloaded successfully.
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/a84d43b8-182e-4518-9631-fff75e015cc2)
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/09d8efbd-4a66-4d8f-90a1-457c66bdadb9)

But I had the following problem while following the tutorial in your Readme.md
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/a4b9f351-1790-42c0-acff-a2cab6152dc3)

**process_begin: CreateProcess(NULL, mkdir -p obj/tournament, ...)  failed.
make (e=2): The system could not find the specified file.
make: *** [Makefile:58: obj/tournament/AxTest.o] Error 2**

I searched some methods on the Internet, but it didn't solve this problem. Could you please tell me how to solve this problem？

**Comment by ZhengyeHan** [comment]
@meatballs 
Help~

**Comment by marcharper** [comment]
We tend to use linux or unix environments and I can confirm that `make` works fine in this case on Ubuntu. I suggest you try emulating a linux environment or use a virtual machine. We don't provide support for using `make` on Windows.
