### ISSUE TITLE
Add original unaltered Fortran file for archival purposes

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/TourExec#3]

**Comment by meatballs** [comment]
Not sure what you mean here. The very first commit includes the files as downloaded. All the modifications take place in subsequent commits.

**Comment by meatballs** [comment]
Is the suggestion to create an earlier release? Perhaps 0.0.1 that points to the initial commit?

**Comment by marcharper** [comment]
as a standalone file so if anyone wants to see what modification were made it's easy to do.
