### ISSUE TITLE
Move the column functions

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/TourExec#4]
The functions KPAVLOVC, KRANDOMC, KTF2TC and KTitForTatC are 'column' functions used in the test program rather that second tournament participants.

We should move them from the strategies folder to the tournament folder. That way, they will no longer be compiled into `libstrategies.so`

**Comment by drvinceknight** [comment]
Why?

It's handy to have them available to us in `axelrod_fortan` which they would no longer be if they're not in `libstrategies.so` (if I understand correctly?). Certainly does no harm and we have the rankings there so we don't need to worry about them being included incorrectly for any analysis.

**Comment by meatballs** [comment]
Just seemed more neat and tidy! Not something I feel overly strongly about, so happy to close this if anyone prefers.

**Comment by drvinceknight** [comment]
I'd personally prefer it as it is, who knows those functions might be handy one day. :)
